name: chronus
description: A time manager project based on pomodoro technique.

dependencies:
  flutter:
    sdk: flutter

  redux: "^3.0.0"
  flutter_redux: "^0.5.2"
  redux_logging: ^0.3.0
  redux_epics: ^0.10.0
  rxdart: ^0.18.0

  flutter_local_notifications: ^0.3.6
  intl: "^0.15.6"
  shared_preferences: "^0.4.2"

  google_sign_in: "^3.0.4"
  
  cloud_firestore: "^0.7.3"
  firebase_auth: "^0.5.12"
  firebase_core: "^0.2.4"
  firebase_database: ^1.0.3
  firebase_analytics: ^1.0.2

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
   - assets/hourglass.png
